SELECT *FROM EMPLOYEES.DEPARTMENTS;

SELECT COUNT(DEPT_NO) FROM EMPLOYEES.DEPARTMENTS;
SELECT MIN(DEPT_NO) FROM EMPLOYEES.DEPARTMENTS;
SELECT CONCAT(DEPT_NAME),CONCAT(DEPT_NO) FROM EMPLOYEES.DEPARTMENTS;
SELECT DEPT_NO,DEPT_NAME FROM EMPLOYEES.DEPARTMENTS
WHERE DEPT_NO <='dOO5';

SELECT *FROM EMPLOYEES.DEPARTMENTS
WHERE DEPT_NO IS NULL; 

SELECT *FROM EMPLOYEES.DEPARTMENTS
WHERE DEPT_NO <="dOO6";

-- DEPT_EMP DATA  

SELECT *FROM EMPLOYEES.DEPT_EMP;
SELECT  EMP_NO FROM EMPLOYEES.DEPT_EMP
WHERE EMP_NO <='10019';

SELECT COUNT(EMP_NO),COUNT(DEPT_NO),COUNT(FROM_DATE),COUNT(TO_DATE) FROM EMPLOYEES.DEPT_EMP;

SELECT ISNULL(EMP_NO) AS EMP_NO,
ISNULL(DEPT_NO) AS DEPT_NO,
ISNULL(FROM_DATE) AS FROM_DATE,
ISNULL(TO_DATE) AS TO_DATE FROM EMPLOYEES.DEPT_EMP;

SELECT DUPLICAT(FROM_DATE) FROM EMPLOYEES.DEPT_EMP;

SELECT EMP_NO, DEPT_NO FROM EMPLOYEES.DEPT_EMP
GROUP BY EMP_NO,DEPT_NO;

SELECT  EMP_NO BETWEEN '10005'AND '10020' FROM EMPLOYEES.DEPT_EMP;

SELECT *FROM EMPLOYEES.DEPT_EMP
WHERE EMP_NO BETWEEN '10010' AND '10050';

SELECT MIN(EMP_NO)  AS EMP_NO, MIN(FROM_DATE)AS FROM_DATE FROM EMPLOYEES.DEPT_EMP
GROUP BY EMP_NO, FROM_DATE;

SELECT SUM(EMP_NO) AS EMP_NO FROM EMPLOYEES.DEPT_EMP;
SELECT COUNT(EMP_NO) FROM EMPLOYEES.DEPT_EMP;
SELECT MIN(EMP_NO) FROM EMPLOYEES.DEPT_EMP;
SELECT MAX(EMP_NO) FROM EMPLOYEES.DEPT_EMP;
SELECT CONCAT(EMP_NO) FROM EMPLOYEES.DEPT_EMP;

SELECT DISTINCT(EMP_NO) FROM EMPLOYEES.DEPT_EMP;
SELECT DATE(EMP_NO) FROM EMPLOYEES.DEPT_EMP;
SELECT DAYNAME(EMP_NO),dayname(DEPT_NO) FROM EMPLOYEES.DEPT_EMP;
SELECT DAY(EMP_NO) FROM EMPLOYEES.DEPT_EMP;
SELECT length(EMP_NO) FROM EMPLOYEES.DEPT_EMP;
SELECT month(FROM_DATE),MONTHNAME(FROM_DATE),YEAR(FROM_DATE),YEARWEEK(FROM_DATE),
 DAYNAME(FROM_DATE),DATE(FROM_DATE)FROM EMPLOYEES.DEPT_EMP;
SELECT BINARY(EMP_NO) FROM EMPLOYEES.DEPT_EMP;
 
SELECT EMP_NO, DEPT_NO,FROM_DATE, TO_DATE FROM EMPLOYEES.DEPT_EMP
WHERE   EMP_NO BETWEEN '10001'AND '10020'
GROUP BY EMP_NO,DEPT_NO,TO_DATE;

--  DEPT_MANAGER DATA

SELECT *FROM EMPLOYEES.DEPT_MANAGER;

SELECT * FROM EMPLOYEES.DEPT_MANAGER
WHERE EMP_NO AND null;

SELECT *FROM  EMPLOYEES.DEPT_MANAGER
WHERE EMP_NO >=110022 AND EMP_NO<=110228;

SELECT nth_value(EMP_NO ,1) OVER(partition by DEPT_NO ORDER BY EMP_NO DESC rows between unbounded 
preceding AND unbounded following ) FROM EMPLOYEES.DEPT_MANAGER;

SELECT TO_DAYS(emp_NO) FROM EMPLOYEES.DEPT_MANAGER;

SELECT  EMP_NO, REPLACE(EMP_NO, 'A','I') FROM EMPLOYEES.DEPT_MANAGER;

SELECT DEPT_NO AS DEPARTMENT FROM EMPLOYEES.DEPT_MANAGER;

SELECT MONTHNAME(FROM_DATE) AS MONTH_HNAME ,
YEAR(FROM_DATE) AS YEAR, 
MONTH(FROM_DATE) AS MONTH,
DATE(FROM_DATE) AS DATE,
DAYNAME(FROM_DATE) AS NAME,
LENGTH(FROM_DATE) AS LENGTH
FROM EMPLOYEES.DEPT_MANAGER;

-- EMPLOYEESS TABLE DATA

SELECT * FROM EMPLOYEES.EMPLOYEES;
SELECT * FROM EMPLOYEES.EMPLOYEES
WHERE GENDER ='M';

SELECT  COUNT(GENDER )FROM EMPLOYEES.EMPLOYEES
WHERE GENDER ='M';
SELECT  COUNT(GENDER )FROM EMPLOYEES.EMPLOYEES
WHERE GENDER ='F';
SELECT *FROM EMPLOYEES.EMPLOYEES
WHERE GENDER ='F'ORDER BY EMP_NO;

SELECT COUNT(EMP_NO) AS EMP_NO_COUNT,
MIN(EMP_NO)AS EMP_NO_MIN,
MAX(EMP_NO)AS EMP_NO_MAX,
AVG(EMP_NO)AS EMP_NO_AVG
FROM EMPLOYEES.EMPLOYEES;

SELECT MONTHNAME(BIRTH_DATE) AS MONTH_HNAME ,
YEAR(BIRTH_DATE) AS YEAR, 
MONTH(BIRTH_DATE) AS MONTH,
DATE(BIRTH_DATE) AS DATE,
DAYNAME(BIRTH_DATE) AS NAME,
LENGTH(BIRTH_DATE) AS LENGTH
FROM EMPLOYEES.EMPLOYEES;

SELECT *FROM employees.employees
WHERE FIRST_NAME LIKE 'A%' AND LAST_NAME LIKE 'A%';

SELECT FIRST_NAME, LAST_NAME FROM EMPLOYEES.EMPLOYEES
WHERE FIRST_NAME LIKE '__A__'  AND LAST_NAME LIKE '__A__';

SELECT COUNT(FIRST_NAME)AS FIRST_NAME_COUNT,
COUNT(LAST_NAME)AS LAST_NAME_COUNT
FROM EMPLOYEES.EMPLOYEES;

SELECT COUNT(FIRST_NAME) FROM EMPLOYEES.EMPLOYEES
WHERE FIRST_NAME LIKE "A%" AND GENDER='M';
SELECT COUNT(FIRST_NAME) FROM EMPLOYEES.EMPLOYEES
WHERE FIRST_NAME LIKE "A%" AND GENDER='F';

SELECT COUNT(LAST_NAME) FROM EMPLOYEES.EMPLOYEES
WHERE LAST_NAME LIKE "A%" AND GENDER='M';
SELECT COUNT(LAST_NAME) FROM EMPLOYEES.EMPLOYEES
WHERE LAST_NAME LIKE "A%" AND GENDER='F';

SELECT *,ISNULL(EMP_NO) FROM EMPLOYEES.EMPLOYEES;
SELECT *,HOUR(BIRTH_DATE) AS BIRTH_DATE_HOURS FROM EMPLOYEES.EMPLOYEES;
SELECT *,ASIN(BIRTH_DATE) FROM EMPLOYEES.EMPLOYEES;
SELECT BIT_LENGTH(HIRE_DATE),BIT_LENGTH(EMP_NO) FROM EMPLOYEES.EMPLOYEES;
SELECT CHAR(HIRE_DATE) FROM EMPLOYEES.EMPLOYEES;

SELECT EMP_NO, BIRTH_DATE,HIRE_DATE FROM EMPLOYEES.EMPLOYEES
GROUP BY EMP_NO;
SELECT * FROM EMPLOYEES.EMPLOYEES
WHERE EMP_NO BETWEEN '10001' AND '10009';

SELECT EMP_NO FROM EMPLOYEES.EMPLOYEES
WHERE  EMP_NO <='10009'OR  EMP_NO >= '10020';
SELECT DISTINCT(FIRST_NAME) FROM EMPLOYEES.EMPLOYEES;

-- SALARIES TABLE DATA  
SELECT *FROM EMPLOYEES.SALARIES;
SELECT SALARY ,EMP_NO FROM EMPLOYEES.SALARIES
ORDER BY SALARY desc, EMP_NO ASC;

SELECT SALARY,EMP_NO FROM EMPLOYEES.SALARIES
ORDER BY SALARY DESC limit 5; 

SELECT  ROUND(AVG(SALARY),2)FROM employees.salaries; 
SELECT EMP_NO, COUNT(SALARY) AS TOTAL FROM EMPLOYEES.SALARIES
GROUP BY EMP_NO HAVING COUNT(SALARY) >=66074 ORDER BY EMP_NO DESC;

SELECT EXTRACT(MONTH FROM SALARY )AS SALARY, SALARY FROM EMPLOYEES.SALARIES;
SELECT EXTRACT(YEAR FROM SALARY )AS SALARY, SALARY FROM EMPLOYEES.SALARIES;

USE EMPLOYEES;SELECT * FROM EMPLOYEES.SALARIES
JOIN EMPLOYEES ON SALARIES.EMP_NO =EMPLOYEES.EMP_NO;

USE EMPLOYEES;
SELECT * FROM EMPLOYEES.SALARIES
INNER JOIN EMPLOYEES ON SALARIES.EMP_NO = EMPLOYEES.EMP_NO;

SELECT * FROM EMPLOYEES.SALARIES
LEFT JOIN EMPLOYEES ON SALARIES.EMP_NO = EMPLOYEES.EMP_NO;

SELECT * FROM EMPLOYEES.SALARIES
RIGHT JOIN EMPLOYEES ON SALARIES.EMP_NO = EMPLOYEES.EMP_NO;

SELECT * FROM EMPLOYEES.SALARIES AS T1
JOIN SALARIES AS T2  ON T2.SALARY= T1.EMP_NO;

SELECT * FROM EMPLOYEES.SALARIES
WHERE SALARY >(SELECT AVG(SALARY) FROM EMPLOYEES.SALARIES);

SELECT SALARY,FROM_DATE FROM EMPLOYEES.SALARIES
WHERE EMP_NO IN ( SELECT SALARY  FROM employees);

SELECT  SALARY,FROM_DATE, SUM(SALARY)
OVER (ORDER BY SALARY ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING ) AS TOTAL
FROM EMPLOYEES.SALARIES ;

SELECT  SALARY,FROM_DATE, MIN(SALARY)
OVER (ORDER BY SALARY ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING ) AS TOTAL
FROM EMPLOYEES.SALARIES ;
SELECT  SALARY,FROM_DATE,AVG(SALARY)
OVER (ORDER BY SALARY ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING ) AS TOTAL
FROM EMPLOYEES.SALARIES ;
SELECT  SALARY,FROM_DATE, MAX(SALARY)
OVER (ORDER BY SALARY ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING ) AS TOTAL
FROM EMPLOYEES.SALARIES ;
SELECT SALARY,FROM_DATE, COUNT(SALARY)
OVER (ORDER BY SALARY ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING ) AS TOTAL
FROM EMPLOYEES.SALARIES ;

SELECT EMP_NO ,ROW_NUMBER() OVER(ORDER BY EMP_NO) AS "ROW_NUMBER",
RANK() OVER (ORDER BY EMP_NO) AS "RANK",
DENSE_RANK () OVER (ORDER BY EMP_NO)AS "DENSE_RANK",
PERCENT_RANK() OVER(ORDER BY EMP_NO)AS "PRECENT_RANK" FROM EMPLOYEES.SALARIES;

SELECT SALARY,ROW_NUMBER() OVER(ORDER BY SALARY) AS "ROW_NUMBER",
RANK() OVER (ORDER BY SALARY) AS "RANK",
DENSE_RANK () OVER (ORDER BY SALARY)AS "DENSE_RANK",
PERCENT_RANK() OVER(ORDER BY SALARY)AS "PRECENT_RANK" FROM EMPLOYEES.SALARIES;

SELECT EMP_NO ,FIRST_VALUE(EMP_NO) OVER(ORDER BY EMP_NO) AS "FIRST_VALUE",
LAST_VALUE(EMP_NO) OVER (ORDER BY EMP_NO) AS "LAST_VALUE",
LEAD (EMP_NO) OVER (ORDER BY EMP_NO)AS "LEAD",
LAG(EMP_NO) OVER(ORDER BY EMP_NO)AS "LAG" FROM EMPLOYEES.SALARIES;

SELECT EMP_NO,LEAD(EMP_NO,2) OVER(ORDER BY EMP_NO) AS "LEAD_2",
LAG(EMP_NO,2) OVER(ORDER BY EMP_NO) AS "LAG_2" FROM EMPLOYEES.SALARIES;

SELECT EMP_NO,FROM_DATE,
CASE
WHEN EMP_NO >10004 THEN 'EXPENSIV NO'
WHEN EMP_NO =10002 THEN 'MODRATE NO'
ELSE 'INEXPENSIVE NO' END AS  EMP_NUMBER
FROM EMPLOYEES.SALARIES;


SELECT EMP_NO,
CASE FROM_DATE
WHEN 1004 THEN 'EXPENSIV NO'
WHEN 1017 THEN 'MODRATE NO'
ELSE 'INEXPENSIVE NO' END AS  EMP_NUMBER
FROM EMPLOYEES.SALARIES;

USE EMPLOYEES;

SELECT e.first_name, e.last_name, dpn.dept_name, t.title, s.salary
FROM employees e, dept_emp dp
INNER JOIN departments dpn
ON dp.dept_no = dpn.dept_no
INNER JOIN salaries s
INNER JOIN titles t
LIMIT 100;



